// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynoxqemobflcfdehmzkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlub3hxZW1vYmZsY2ZkZWhtemtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTk4OTQsImV4cCI6MjA2NjY5NTg5NH0.Zw2Ybj8pzhm0yWdu_K1UxmWtXa1k9Vc_Zml7brPghoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);